openapi: 3.0.3
info:
  title: Tekilator 
  description: |-
    This api document give's the usage of how to use the tekilator api 
  
  contact:
    email: aniket.dev.tech@gmail.com
  
  version: 1.0.0
externalDocs:
  description: Find our more about me
  url: https://github.com/TRUTHANIKET
servers:
  - url: https://tekinatranslate.onrender.com

paths:
  /translate:
    post:
      tags:
        - Translate
      summary: Requesting for translated text
      description: Request for text
      operationId: updatePet
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
                type: object
                properties:
                  text:
                    type: string
                    
                    example: hi this is aniket
                  from:
                    type: string
                    example: en
                  to:
                    type: string
                    example: "hi"
                    xml:
                      name: addresses
                      wrapped: true
                    


        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  translations:
                    type: object
                    properties: 
                      text:
                        type: string
                        example: "हाय यह अनिकेत है"
                      to: 
                        type: string
                        example: "hi"   
                          

                    
            
        '400':
          description: Invalid ID supplied
        '404':
          description: file not found
        '405':
          description: Validation exception
