name: Deploy documentation

on:
  push:
    branches:
      - master
jobs:
  deploy-doc:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: a973b27b-5c03-418d-99ad-20c6f89c231c
          token: ${{secrets.BUMP_TOKEN}}
          file: apispec.yml